### ISSUE TITLE
NAT routing conflicts with Hyper-V vms NAT

### ISSUE THREAD

**Issue by exelix11** [micahmo/WgServerforWindows#110]
Windows NetNat currently supports a single NAT instance, this means that using WgServer takes it over preventing HyperV VMs from using the NAT feature.

Ms [proposed solution](https://learn.microsoft.com/en-us/virtualization/hyper-v-on-windows/user-guide/setup-nat-network#multiple-applications-using-the-same-nat) is to configure a single NAT shared by multiple adapters.

I'm fine with WgServer managing the NetNat configuration, however i'd like to ask for an "advanced configuration" option where the user can set a custom value  for the `InternalIPInterfaceAddressPrefix ` option (with sanity checks to make sure it includes wireguard's IP range), this way the NAT can be shared by multiple network adapters.

**Comment by micahmo** [comment]
Hi @exelix11,

The NAT network created by WS4W already sets the value of `InternalIPInterfaceAddressPrefix` based on the server address range.

![image](https://user-images.githubusercontent.com/7417301/232481087-9fdf121d-6fd0-4f37-bd64-64b22eac05f0.png)

It may not be ideal, but could you just expand this range in WS4W to include both your desired Hyper-V network and your WireGuard network? You'll just have to make sure clients don't overlap.

---
#### Code reference
https://github.com/micahmo/WgServerforWindows/blob/7375aeda0e2fd3e8f40b2da2fd33b245931973da/WgServerforWindows/Models/NewNetNatPrerequisite.cs#L110-L111

**Comment by exelix11** [comment]
I did try that already but it changes wireguard's adapter ip range in a way that partially overlaps with hyperv's one. Not sure if that can cause side effects.

**Comment by exelix11** [comment]
I mean yeah I could try but I'd like my VPN to be reliable and not have to do debugging the next time i need it 😅

For the time being I'm just not using hyperv but I'd like for this be implemented as apparently it's how Ms says it's meant to be done (arguably, an hacky solution on their end)

**Comment by micahmo** [comment]
Hey @exelix11. Thanks again for the suggestion and explaining the use case. Let me run this proposed design past you to get your feedback and to give it the best possible chance of working as you intended (so you don't have to be troubleshooting things!).

As before, you specify your desired WireGuard network range in the server configuration. The WireGuard adapter will get the first address in this range.

![image](https://user-images.githubusercontent.com/7417301/232929467-596392a2-698e-4039-8ee7-25bf5d2b64f0.png)

![eyLDpGwNlZ](https://user-images.githubusercontent.com/7417301/232929496-0dfe9691-b2fb-40c4-beb1-3c792a374a99.png)

Then in the NAT Routing additional options, you can specify a custom range for the NAT network. It must be a superset of the WireGuard network. You can do this before or after enabling NAT routing.

![8NGWHl6CCa](https://user-images.githubusercontent.com/7417301/232929516-705954d7-8106-449c-be92-140a42671a27.png)

![WgServerforWindows_7d11KwS71I](https://user-images.githubusercontent.com/7417301/232929646-9b251c02-df57-4fe9-bbb3-7f1b4490c11c.png)

![WindowsTerminal_v37KZyRKTI](https://user-images.githubusercontent.com/7417301/232929656-64a5ac65-7270-4092-8e90-99e726428df5.png)

I tested this with WireGuard at the bginning of the NAT range (10.253.0.0/24 and 10.253.0.0/16) and also in the middle (10.253.0.0/24 -> 10.252.0.0/15). The only thing that didn't seem to work was using a Class A as the NAT range (10.0.0.0/8).

Note that I'm not testing the Hyper-V part. As far as WS4W is concerned, if the NAT range is what you want, then it's good.

Let me know what you think and if there's anything in particular I should try.

**Comment by exelix11** [comment]
Yes, this is correct.
I also did test with hyperv and can confirm this allows forwarding packets from both wireguard and vms at the same time.

To provide more context of others with similar issues my setup is as follows:
- wireguard as 10.10.1.0/24 (i don't think the address of the virtual wireguard nic matters but it's  .1 cause I don't see any reason to change it)
- I created a new internal hyperv switch on the 10.10.2.0/24 subnet (this means I'm not using the default "nat" one)
- finally i created a 10.10.0.0/16 nat with New-NetNat

And everything seems to be working fine but doesn't survive reboots cause wgserver notices the nat changed and for some reason does not assign an ip wireguard's interface. A simpler fix would be to ignore the condition but I'd prefer the increased reliability of wgserver supporting this configuration directly. 

I did not test using hyperv builtin "nat" because that is also shared by docker and wanted to try one thing at a time.
Only downside of creating a new adapter for this seems that hyperv will not use a dhcp server and I have to statically configure vm ips.

**Comment by micahmo** [comment]
Thanks for the feedback! I tested your setup with your address ranges (minus the Hyper-V switch, so steps 1 and 3), and WireGuard worked just fine, including after a reboot.

I went ahead and published this feature in [v2.0.10](https://github.com/micahmo/WgServerforWindows/releases/tag/v2.0.10). Feel free to give it a shot and let me know if it works for you.
