### ISSUE TITLE
Acces wgserver ip from lan.

### ISSUE THREAD

**Issue by BurmazDaniel** [micahmo/WgServerforWindows#121]
Hi and first i want to say that i am using your application since version 1.6. It is a great app.

I have a problem with this type of wireguard implementation on windows server and windows 10. I have no problems configuring all steps, i have internet connection on my clients but i cannot acces any client from my lan. I can only acces clients from the server itself. I set a static route in my router as i should do but i still dont get a respone from ping. All network interfaces are set to private and firewall is off. 
I tried using ubuntu server with pivpn, created my static route and i can acces my client(10.253.0.2) from any of 192.168.0.0/24 devices from my lan.
I've been searching for a solution for about half a year. What am i doing wrong?
Thank you!

**Comment by micahmo** [comment]
Hi @BurmazDaniel,

Let me see if I understand your scenario. 

You have a client connected to a server. The client can talk to the server and talk to the internet through the server just fine. The server can talk to to the client. However, other machines on the _server's_ LAN cannot talk to the client, is that right?

To be honest, this seems like an inherent problem with NAT routing. If there are multiple machines behind NAT, it's hard to target one from the outside. Generally either connections are initiated from inside, or you need some kind of port forwarding (and I don't know if Windows' primitive NAT implementation supports that, although [you can check](https://learn.microsoft.com/en-us/powershell/module/netnat/)).

Maybe it would help to put the other systems on your LAN on the same WireGuard network?

**Comment by BurmazDaniel** [comment]
> 

![323586908_203203122250566_8671492090689461541_n](https://github.com/micahmo/WgServerforWindows/assets/20422068/a7f935b2-d4cb-4962-ae61-b71d4cb8eacc)

I hope this is a better way to undestand. On that phone runs a webserver/ webcam server and i can acces it from the wireguard server(green line) but i cannot acces my phone from the other devices connected to my router(red line).

**Comment by BurmazDaniel** [comment]
You're the best!
Thank you so much for all your help! Unfortunately port proxy is the only workaround in windows but this will help me alot for my bachelor's degree.
