### ISSUE TITLE
Wireguard connected - handshake received - no internet access

### ISSUE THREAD

**Issue by chris0101** [micahmo/WgServerforWindows#128]
Hi,

I setup a wireguard server on my friends pc for #reasons. 

Anyway , i followed all the steps and all the green ticks are present, it worked fine for about a week, when i connect now i can see in the logs the handshake is received ;

2023-08-07 14:10:18.328: [TUN] [xxxxxxx] Receiving handshake response from peer 1 (xxx.xxx.xx.xx.xx)
2023-08-07 14:10:18.328: [TUN] [xxxxxxx] Receiving handshake response from peer 1 (xxx.xxx.xxx.xxx)
2023-08-07 14:10:28.447: [TUN] [xxxxxxx] Receiving keepalive packet from peer 1 (xxx.xxx.xxx.xxx)

So i am technically connected, but now i have no internet access.

I can't troubleshoot right now as he'd actually not home for me to tinker with it.

Is this a simple case of the internet sharing not working properly ? im guessing he rebooted his PC at some point , but i did setup the persistent internet sharing ( i've tested this on my laptop and it worked fine after a reboot so assumed it would be the same for his ) 

My go to move next is when hes back get him to run the persistent internet task in the task scheduler , do you think it didn't run for some reason? or maybe ran too early?

**Comment by micahmo** [comment]
Hey @chris0101, sorry to hear about this! I think you're on the right track with your troubleshooting ideas. The fact that you get a handshake is good, and it just sounds like internet sharing is not working properly. And yes it's entirely possible that the task ran too soon, depending on how long it takes for his network adapter to initialize.

When he's available, you might want to experiment with setting a delay on the Windows task. You can do this either directly in Task Scheduler or in the WS4W UI (although note that the latter requires you to disable and re-enable the task through the UI).

**Comment by chris0101** [comment]
Yep perfect that's what I'll try. Thanks for the response. Will let you know if it works when he's back

**Comment by chris0101** [comment]
So as predicted when I finally got around to this the internet sharing had the X on it. Ive added a 30 second delay to the persistent Internet task , should work ...
