### ISSUE TITLE
IPV6 Setup

### ISSUE THREAD

**Issue by Jayspek** [micahmo/WgServerforWindows#135]
I'd like to be able to use IPV6 through the tunnel as well as IPV4. IPV6 is working on the client and the server, and I can connect to the wireguard server using IPV6. However, no matter what I do I can't get it to pass on online ipv6 test. I've tried pretty much every tutorial on the first page of google results, but there all for various linux distros and don't transfer over perfectly.

Has anyone done this successfully, or know how? I'm at a loss for how to proceed at the moment.

**Comment by micahmo** [comment]
Hey @Jayspek, I'm not sure if I'll be too much help here. I was hoping someone in the community would chime in, but that hasn't happened yet!

Just to clarify about your scenario, you have an IPv6 WAN IP, which you are using to connect from outside your network to your WG network. However, subsequent outbound connections initiated by devices on your WG network appear to originate from your IPv4 WAN address. Is that about right?

**Comment by Jayspek** [comment]
Yep, that's correct! And if you force it to use IPV6, it fails outright. Its unfortunately become irrelevant for me, as it turns out my ISP rotates my IPV6 address almost every day, and my router doesn't have a way of dynamically updating its firewall rules.
