### ISSUE TITLE
Is there a way to disable the wireguard server

### ISSUE THREAD

**Issue by Brandonv101** [micahmo/WgServerforWindows#140]
Is it possible to disable the wireguard server on windows after I am finished using it. Sort of like an on and off switch?

**Comment by micahmo** [comment]
Hey @Brandonv101, thanks for the question! At this time there's isn't a single on/off switch. But you can disable WireGuard with two clicks, if that's not too much. 😆

1. Turn off your internet sharing of choice (either "Disable NAT" or "Disable Internet Sharing").
2. Turn off the WireGuard tunnel service ("Uninstall tunnel service").

See #53 for more info.

**Comment by Brandonv101** [comment]
Hi there,

Thanks! That works fine.
