### ISSUE TITLE
Call Server Status Display Directly

### ISSUE THREAD

**Issue by MichelfrancisBustillos** [micahmo/WgServerforWindows#142]
Not an issue per say, more of a functionality question. 
Is it possible to call the Server Status Display directly via CMD or via an .exe? I would like to do this to have it automatically run on startup for an easy way to tell what clients are connected and if the server is running.

**Comment by micahmo** [comment]
Hey @MichelfrancisBustillos, great question! WS4W is already invoking a command line behind the scenes to show what you see in the UI. Assuming `wg.exe` is in your PATH, you can run this command.

![image](https://github.com/micahmo/WgServerforWindows/assets/7417301/16b32414-648b-41d5-a34c-d0f297366770)

Now if you want it to continuously update like it does in WS4W, that would be a bit more tricky, but you can try something like this in PowerShell.

``` powershell
while ($true) { clear; wg.exe show; Start-Sleep 1 }
```

Hope that helps!
