### ISSUE TITLE
Enable configuration of PersistentKeepalive in client configuration

### ISSUE THREAD

**Issue by brandonros** [micahmo/WgServerforWindows#148]
https://unix.stackexchange.com/questions/714145/wireguard-not-able-to-connect-after-a-few-minutes

**Comment by micahmo** [comment]
Thanks for the suggestion! As a workaround, you can set the Persistent Keepalive in the server config. But it will apply globally to all clients. It should be moved to a per-client config option.

**Comment by brandonros** [comment]
am I right to say that if you said it manually in the config file for the clients that it stands to be overwritten the next time any change is made via the GUI?

**Comment by micahmo** [comment]
Yes you are right. If you press the Save button in either the Server or Client config, it will rewrite the WireGuard files according to what it thinks they're supposed to be.

**Comment by micahmo** [comment]
Hey @brandonros, this feature should be added in the latest release, [v2.0.11](https://github.com/micahmo/WgServerforWindows/releases/tag/v2.0.11). Feel free to check it out and let me know if this works for you.

**Comment by brandonros** [comment]
@micahmo thank you for all of the hard work you do for the community. will test and report back if there are any issues. highly appreciate it.

**Comment by brandonros** [comment]
@micahmo hey, sorry to bother you. i'm 99% sure on latest release this doesn't work as expected 100%. in `clients_wg` folder the `[Peer]` is missing `PersistentKeepalive = 25` for example and it gets overridden everytime a change is made in the UI

**Comment by brandonros** [comment]
https://github.com/micahmo/WgServerforWindows/blob/55e9197cfeb9f60c6def32ff268ddbc97916e20a/WgServerforWindows/Models/ClientConfigurationsPrerequisite.cs#L238

If I had to guess it was getting dropped there
