### ISSUE TITLE
It closes by itself after a while of not using it (Win11).

### ISSUE THREAD

**Issue by Paulorg95** [micahmo/WgServerforWindows#149]
Hi. It works correctly but if I am not using WireGuard for a few minutes WS4W closes itself and the vpn does not work until I enter the pc and open it again. Does anyone know why?

**Comment by micahmo** [comment]
Hi @Paulorg95, I'm sorry to hear you're experiencing this issue! WS4W doesn't need to be running in order for the WireGuard VPN to function. It only exists to help with configuration. What needs to be running is the WireGuard server. 

* Check that you have the WireGuard app running in your system tray.
  ![image](https://github.com/micahmo/WgServerforWindows/assets/7417301/fef56f0a-ef1b-4c44-9353-df3aa70a1fe2)
* Check that the WireGuard process is running.
  ![image](https://github.com/micahmo/WgServerforWindows/assets/7417301/74268b07-dd7e-4d82-b832-dbe3f0096346)
* Check that there are some logs in the UI.

Is it possible that your PC is going to sleep or some other app is killing WireGuard?

**Comment by Paulorg95** [comment]
Hi. I checked the service and It was stopped, now everything works.

Thank you for your help :)

**Comment by micahmo** [comment]
Great, glad to help!
