### ISSUE TITLE
Invalid class error after splash [already solved]

### ISSUE THREAD

**Issue by harverto** [micahmo/WgServerforWindows#158]
No drama, it's not a issue, it's a wmi corruption, but I didn't know where to post it
It's already over, but I got crazy trying to resolve an annoying error "Invalid Class" after splash screen.
I've had installed a lot of dot net libraries, 32/64/desktop/server versions.. and I was near to lose hope
The solution is [here](https://github.com/SafeExamBrowser/seb-win-refactoring/issues/746)
And if you don't want to click, follow this steps:
Procedure to potentially fix WMI corruption:

- Close all Apps run cmd as admin

- Disable and stop the WMI service

sc config winmgmt start= disabled
net stop winmgmt

- Run the following commands.

Winmgmt /salvagerepository C:\WINDOWS\System32\wbem
Winmgmt /resetrepository C:\WINDOWS\System32\wbem

- Re-enable the WMI service and then reboot the server to see how it goes.

sc config winmgmt start= auto

- restart PC

Thank you to all community.

**Comment by micahmo** [comment]
Thank you so much for sharing this issue and resolution! I'm not sure I would've been able to figure this one out. 😆

**Comment by vikaasridevianti** [comment]
its works! thankyou
