### ISSUE TITLE
Donation Button

### ISSUE THREAD

**Issue by crack00r** [micahmo/WgServerforWindows#32]
Maybe you could add a donation button somewhere here on github?

This project is epic!

**Comment by micahmo** [comment]
Thank you, that's very kind of you to suggest!

I'm hesitant to accept donations, as I'm afraid that it will make some people feel like they can pay for features or support. Unfortunately, this is mostly a hobby project, and I don't think the amount of time I'm able to spend on it justifies donations.

We'll see. 😊
