### ISSUE TITLE
Allowed IPs should be editable in client configuration

### ISSUE THREAD

**Issue by okastl** [micahmo/WgServerforWindows#36]
Hi,
"Allowed IPs" is a wireguard client configuration. At the moment is is set in "Server Configuration".
It may be nice to set it up once in "Server Configuration" but as a peer parameter it really should be in "Client Configuration". Maybe with a button "populate from server"?

This has fairly low priority, as "Allowed IPs" can be changed in the client software anyway, but it just looks ... "right" to be in "Client Configuration". ;)

**Comment by micahmo** [comment]
This has been added in [v2.0.1](https://github.com/micahmo/WgServerforWindows/releases/tag/v2.0.1).
