### ISSUE TITLE
DNS Search Domain

### ISSUE THREAD

**Issue by GoodiesHQ** [micahmo/WgServerforWindows#50]
The wireguard docs say this:

> DNS — a comma-separated list of IP (v4 or v6) addresses to be set as the interface’s DNS servers, or non-IP hostnames to be set as the interface’s DNS search domains. May be specified multiple times. Upon bringing the interface up, this runs ‘resolvconf -a tun.INTERFACE -m 0 -x‘ and upon bringing it down, this runs ‘resolvconf -d tun.INTERFACE‘. If these particular invocations of resolvconf(8) are undesirable, the PostUp and PostDown keys below may be used instead.

In the current platform, when I add a non-IP address to the "DNS Servers" list, it is invalid. To be honest, I think this behavior is fine. I think there should be an additional field for search domain(s) that, if filled, simply joins the entries as comma-separated values to the DNS line of the configuration.

**Comment by micahmo** [comment]
Hey @GoodiesHQ, thanks for the suggestion! I agree that Search Domains should have their own field, because they're really describing a separate, pre-DNS lookup operation.

BTW, those in the Windows world might be more familiar with the term "DNS suffixes".

**Comment by micahmo** [comment]
Hey @GoodiesHQ, this feature should be available in the latest release, [2.0.1](https://github.com/micahmo/WgServerforWindows/releases/tag/v2.0.1). I verified that the the search domains get appended to the DNS field and can be successfully imported into a client instance of WireGuard. Maybe you can verify whether the behavior works as expected (although at that point, it's on WireGuard 😊).

Thanks!
