### ISSUE TITLE
Migrate config to a new server

### ISSUE THREAD

**Issue by rohanb1965** [micahmo/WgServerforWindows#52]
Hi Micah 
Is there an easy way to migrate the existing running config to a new server without having to recreate every client.
Thanks

**Comment by micahmo** [comment]
Hey @rohanb1965, I think this should be possible without too much effort. On the old server in WS4W, press the dropdown next to "Edit server configuration" and choose "Open server configuration directory". This will open the directory containing all of the configuration data. You can copy the four folders, `clients_data` , `clients_wg`, `server_data`, and `server_wg`. The rest of the data is not critical to WireGuard, but you can copy it as well if you want.

On the new server, install WS4W. Most likely the corresponding `AppData` folder won't exist yet, so you have a few options here. Choose one.
1. Just create it manually. Assuming you follow the same directory pattern as on the old server, this should work fine.
2. Walk through the WS4W configuration steps as though you were configuring a new server (i.e., edit the server config and create at least one client). This should set up the necessary directories.
3. For both the server and client config, press the dropdown, and choose "Change configuration directory". This lets you point to any folder, so you don't necessarily have to put the old data into the same place. However, this might require that you've done option 2 above, so you might just go that route instead.

Then paste (overwrite, if needed) the files and folders copied from the old server. Finally, you might want to go back into the WS4W UI, edit the server config, and save it. That should force WireGuard to resync the updated config files. As always, you can View the server status to verify that it knows about all the right peers.

One big caveat to keep in mind here is that your clients have been configured to point to a particular server address. If you used an IP address and you're switching to a new server with a different IP, you'll have to update all of them. If you used a DNS name, of course you just need to update the relevant DNS record.

Let me know if that helps.

**Comment by rohanb1965** [comment]
Hi @micahmo 
Thanks for you quick response. 
Followed this and it works perfectly.
This makes life much easier as I thought your answer might be no you cant.
