### ISSUE TITLE
About .net core!

### ISSUE THREAD

**Issue by tiny-andr** [micahmo/WgServerforWindows#55]
I like this project very much, but when I installed it on my work PC recently, it kept saying that the .net core component was missing. What puzzled me was that the software did not indicate what version of the net component was missing. I tried to download several versions on the web, but it didn't work. 

The pop-up window prompts "would you like to download...", I click yes, and no browser window pops up.
May I ask which version of .net core components do I need to install?

**Comment by tiny-andr** [comment]
Finally I found the result! . After I installed the .NET Core 3.1 SDK (v3.1.422), the software worked fine. My system is windows 11 pro system. Give others a reference.

**Comment by micahmo** [comment]
Hey @tiny-andr, thanks for the comment!

The installer is supposed to install the .NET Core Desktop Runtime, but it's possible that the check is different on Windows 11.

Do you recall if the installer prompted you to install .NET Core Desktop Runtime?

**Comment by tiny-andr** [comment]
I've only had one time when installing without any prompts. But it's been so long, I've almost forgotten about it. It has been working fine for the next few versions.
