### ISSUE TITLE
Maybe we increase the grouping function of the client management page.

### ISSUE THREAD

**Issue by tiny-andr** [micahmo/WgServerforWindows#56]
Maybe we increase the grouping function of the client management page.
Each client occupies a large part of the area. When there are many people, it will be very crowded. You can make each of them in a specific group, and you can also fold the configuration file information in the group. , expand it when you want to view it.
This will make managing the client a lot easier.

**Comment by micahmo** [comment]
Hi @tiny-andr, I have added a few improvements to the client configuration page. You can now collapse/expand each client (which will be remembered), apply a filter to narrow down the total list, and see a count. I didn't go as far as adding grouping yet, but I thought this would be a good start. In case you still use WS4W, feel free to grab the latest version and let me know what you think.

**Comment by tiny-andr** [comment]
> Hi @tiny-andr, I have added a few improvements to the client configuration page in [2.0.7](https://github.com/micahmo/WgServerforWindows/releases/tag/v2.0.7). You can now collapse/expand each client (which will be remembered), apply a filter to narrow down the total list, and see a count. I didn't go as far as adding grouping yet, but I thought this would be a good start. In case you still use WS4W, feel free to grab the latest version and let me know what you think.

I would say this new feature is simply awesome!
I've been using wg4win. (I found this amazing app on 2.0.2, I'm still using 2.0.6, I also made a how-to video for this app, I'll be upgrading to 2.0.9! )

**Comment by micahmo** [comment]
I'm glad to hear about your positive experience! I would be interested in seeing the video if you care to share. 😊

If you are happy with the new client configuration UI in 2.0.7+, please feel free to close this issue. Thanks!

**Comment by tiny-andr** [comment]
> I'm glad to hear about your positive experience! I would be interested in seeing the video if you care to share. 😊

[https://www.bilibili.com/video/BV1zW4y1t7VX/?spm_id_from=333.337.search-card.all.click&vd_source=6862e76ca3779714a145f9484d901d6b](url)

This is a video based on wg4win version 2.0.1 and made in Chinese language (because this software currently only has an English interface language), the overall content is for beginners. There are many users who are not very good at command line operation that need this (like me), and I have recommended this application to many people.
