### ISSUE TITLE
Restrict lan access

### ISSUE THREAD

**Issue by kababoom** [micahmo/WgServerforWindows#57]
Thank you for creating this wonder full repo, installation and configuration made extremely easy. 
Surprisingly this VPN on Windows 10 is faster than on Ubuntu (virtual machine with same hardware etc).

One question, how do I go about limiting access to certain networks in my LAN? I assume via local firewall rules but am not sure.

-M

**Comment by micahmo** [comment]
Hi @kababoom.

Thanks for the compliments! However, the read credit goes to WireGuard for the excellent VPN technology. My simple app just helps to configure it on Windows.

The same is true for any advanced questions like how to limit LAN access. That's really a question for WireGuard that you can check in their documentation. However, I will try to help anyway.

One thing you can do is modify the "Allowed IPs" field in the Client Configuration. By default, it's set to `0.0.0.0/0`, which means that a request to any IP address in that range (which is everything!) will be routed over the VPN connection. If you set it to a specific subnet, like `192.168.1.0/24`, only requests to IPs in that range will be routed.

The downside to that approach is that it's a client-side setting, so you can enforce it on the server. A rogue client could change the value to `0.0.0.0/0` and then access the whole subet.

If you want to do something on the server side, you may have to manipulate one of the two ways that network connectivity is shared between the WireGuard adapter and the main network adapter on your machine. A quick search did not return anything obvious to me, but you're welcome to look more. This is digging deep into how Windows networking works. 😊 You can look up solution for both of the two approaches that WS4W allows: NAT (look new New-NetNat) or Internet Connection Sharing. In both cases, they automatically give you whatever access the adapter that you're sharing has.

The other option, like you suggested, may be to limit the abilities of the adapter itself with something like a firewall.

Sorry I don't have all the details on that!

**Comment by kababoom** [comment]
Hi @micahmo,

Thanks, yes from client side works fine but indeed I'm looking for something from server side. Will investigate further on firewall settings and NetNat when I got the time...

Will comment on this issue when I find something that perhaps will help others looking for the same.

-M

**Comment by gmipf** [comment]
Are there an news on that topic? I have tried blocking outgoing connections from Wireguard peers to my local network in the Windows Firewall but the rules are ignored. I only can block the server/host itself to other local IP or peers. Is the Windows Firewall maybe unable to block traffic inside the vSwitch NAT device?
