### ISSUE TITLE
Always on

### ISSUE THREAD

**Issue by ohitstom** [micahmo/WgServerforWindows#59]
Maybe i misreading the readme, but is there a way to disable the tunnel?
At the moment it seems you just always be on

**Comment by ohitstom** [comment]
"This step also creates a Windows Task to make the network Private automatically on boot. You may disable the Task via the dropdown."

My apologies.

**Comment by micahmo** [comment]
Hi @ohitstom, no apologies necessary! The statement you quoted from the README really only refers to the Private nature of the network, and whether it remains in that state upon boot. However, if you're looking for a more straightforward and complete way to disable/re-enable the tunnel at will, take a look at [#53](https://github.com/micahmo/WgServerforWindows/issues/53#issuecomment-1181805859).

The two steps in my comment on that issue should help.

**Comment by ohitstom** [comment]
Ty!
