### ISSUE TITLE
NAT Routing - Doesn't start automatically (task not being created)

### ISSUE THREAD

**Issue by ualdayan** [micahmo/WgServerforWindows#75]
I have v2.0.5 and it works great except for after the computer restarts.  NAT Routing always stays disabled until I start up WS4W and click enable again.  I don't see anything under services about starting up automatically - what would the command be to start NAT routing so that I could add it in manually as an Automatic (Delayed) start service?

**Comment by micahmo** [comment]
Hey @ualdayan, your issue sounds similar to #28 where the given adapter is not quite ready to handle a NAT routing network immediately upon boot. There is already a feature that attempts to automatically re-enable NAT, which is controlled by a Windows Task, but the timing may not work for every scenario. Fortunately, you can tweak it manually or simply create your own.

If you just want to enable/disable the Task from the WS4W, you can do so from the dropdown button next to Disable NAT.

![image](https://user-images.githubusercontent.com/7417301/214146000-37f07646-a270-475d-993e-381e9b154f30.png)

From Task Scheduler, you can look for a Task with the name `WS4W Set NetIPAddress (1048541f-d027-4a97-842d-ca331c3d03a9)`. From there you can do whatever you want (add a delay, etc.). Or copy the command and create your own task. The command simply invokes the WS4W CLI as such.

``` powershell
ws4w.exe setnetipaddress --serverdatapath C:\Users\micah\AppData\Roaming\WS4W\server_data\wg_server.conf
```

Hope that helps!

**Comment by micahmo** [comment]
Hey @ualdayan, version [2.0.9](https://github.com/micahmo/WgServerforWindows/releases/tag/v2.0.9) adds the ability to define a custom delay for the Windows boot tasks. I hope that plus the command I provided earlier solves your issue.
