### ISSUE TITLE
Remove the need for Private key to be generated on Server side

### ISSUE THREAD

**Issue by felix920506** [micahmo/WgServerforWindows#76]
It would be nice if I could generate the private key on the client side then only feed the server software the public key.
The control panel doesn't allow me to enter a public key into the public key field.
I can generate a private key then delete it from the control panel but I don't feel comfortable sending private keys over the internet.

My Software Version: v2.0.5

How I would like it to be changed:
Allow entering values into the Public Key field.

**Comment by micahmo** [comment]
Hi @felix920506, Thanks for the suggestion and great point. I have made the public key field editable in version 2.0.6. Can you try it out and let me know if this satisfies your request?

**Comment by felix920506** [comment]
I have downloaded and installed v2.0.6 on my VPN server and I can confirm that it satisfies my request. Thanks.
