### ISSUE TITLE
I have no internet or network conection and everything seems ok

### ISSUE THREAD

**Issue by koliflores** [micahmo/WgServerforWindows#98]
Hi good night. I would like to thanks every people make this project true! its a great job.

Buy i have a problem i can't resolve.
I have Windows 10 PRO 22H2 and i have installed the WS4W 2.0.8.0 and follow the instructions...
Every parts of the list are in green, NAT Routing included

I opened the udp (also TCP) port to the phisical LAN adapter

But when i connect from the phone to my computer i have no internet on the phone, 
I dont know what to do and i need some help please!!!

What should i do???

sorry about my english!
A lot of thanks!

**Comment by koliflores** [comment]
![image](https://user-images.githubusercontent.com/125513814/219199983-c640ff96-aaa4-4331-a945-ddd60e8767b3.png)

**Comment by micahmo** [comment]
Hi @koliflores,

Can you view the server status while you connect your phone? Do you see a successful handshake?

Can you also send screenshots of your server and client configs (if you feel comfortable doing that)? Remember to blank out the keys and public addresses.

**Comment by koliflores** [comment]
hi, thanks for your answer, i'll show you everything you need, i'm so interested to use this vpn server.

I can't see the handshake or i don't know how to see, when i connect from my phone to the server, i have no internet, on the phone.
I make a ping to mi client ip and it answers but when i make ping to the server, it doesn't respond, it doesn't work. all packets lost.

Here is my server config:
![image](https://user-images.githubusercontent.com/125513814/219473356-14f4dfa0-227f-4a0d-91f3-40c0edd7b5d7.png)

And here is my client config:
![image](https://user-images.githubusercontent.com/125513814/219474280-8f9988d9-dc5a-4724-9232-7efe2e47bafb.png)

The field "Latest Handshake" is in blank

My ethernet adapter has 192.168.1.3  private ip (manually added)
And the port on the router is opened
![image](https://user-images.githubusercontent.com/125513814/219474948-ebeab8e2-f28c-437c-b8c5-065b7c04803f.png)

This is an screenshot from my phone with connection started, i don't have internet and in the browsers appears DNS_PROBE_STARTED
![image](https://user-images.githubusercontent.com/125513814/219476244-cec0d8b3-6208-4af1-b223-b4cd8f18c0f3.png)

And this is the SERVER STATUS... when the phone has the connection active
![image](https://user-images.githubusercontent.com/125513814/219477031-aeb99f2a-60ca-4679-a4db-dfd6602eac92.png)

Sorry about this large post, but i'm very interested to have my own vpn server with WS4W
Thaks a lot. I hope you could help me!!
THANKS!!!!!

I also tried with 10.253.0.0 range of private IPs

**Comment by micahmo** [comment]
Thanks for all the details! Nothing stands out to me as obviously wrong, so this may be hard to diagnose.

The fact that there's no mention of a handshake in the server status is interesting. It means the clients can't even make the initial connection to the server (nevermind getting internet access). Here's an example of what a good handshake would look like.

![image](https://user-images.githubusercontent.com/7417301/219489955-7ae08868-a025-4e48-9fb1-49d4ef728103.png)

Here are a couple things to check. Run these commands in PowerShell and let me know the results.

``` powershell
Get-NetNat -Name wg_server_nat

Get-NetNatExternalAddress -NatName wg_server_nat

netstat -anob | select-string wireguard.exe -context 1,0
```

**Comment by koliflores** [comment]
Hi, good night thanks for your answer!!

![image](https://user-images.githubusercontent.com/125513814/219492766-eb415cf8-050c-47f1-a64f-1450fd67661b.png)


![image](https://user-images.githubusercontent.com/125513814/219492982-d1e75dc3-f0d9-482d-a986-c93280dbcc10.png)


![image](https://user-images.githubusercontent.com/125513814/219493141-8f345a41-a462-4bbe-9b80-653cfef7ca48.png)


I don't know what i'm doing!!
I'm in your hands!!

**Comment by micahmo** [comment]
I am also not always sure what I'm doing. 😄

Can you open the WireGuard application and go to the Logs tab and then attempt to connect the client?

This is what a successful handshake looks like.

![image](https://user-images.githubusercontent.com/7417301/219494939-dcf65ae8-b2c9-441f-91bb-ba3c4fa92c73.png)

**Comment by koliflores** [comment]
HI, here it is

![image](https://user-images.githubusercontent.com/125513814/219495540-e855be44-5977-4e14-9025-281b788d5057.png)

Mi Android phone is connected with 4g to the Wireguard config

![image](https://user-images.githubusercontent.com/125513814/219496486-3c8f5f8a-9eb6-40b9-a2a9-47b208541752.png)

**Comment by micahmo** [comment]
Hey @koliflores, I'm a bit stumped here as everything you have looks good!

With regards to the WireGuard logs, did you attempt to connect your client while watching the logs?

The only other thing I can think of is that your mobile or home ISP have blocked that port. Could you try another port?

P.S. Your last screenshot shows your full domain name. Not sure if you want to hide that.

**Comment by koliflores** [comment]
Hi @micahmo I don't have word to thanks for your answers!!!
A lot of thanks!!!!

With your answer I made my own investigation and finally I think I know what's the problem!!!!

When you said me that everything was right I used an Android application called "fing" to see if the ports were opened!!!!

It was a surprise to see that any of my opened ports were open!!!!

I was reading across the internet about my is and my router model and there was the problem... I think!!

I am under a service called CG-NAT 
That service provide me an public IP but shared with other clients and it has closed all ports!!!!

I called my ISP to remove me from this CG-NAT service and in 24 hours I'll be out and I'll have my own public IP. 

Then I could open the ports I need to my computer and I hope the VPN server and other services will work fine!!!!

I'll tell you every step that happens!!!!!

A million of thanks!!!!!!!!!!!!

**Comment by micahmo** [comment]
Hey @koliflores, I'm so glad to hear this update. Yes, CGNAT can be very problematic when it comes to exposing your home services. I assumed based on your router screenshot that you had had luck opening ports before, but maybe not. Anyway, having a dedicated IP will definitely help. Let me know if you're able to get it working after that!

**Comment by koliflores** [comment]
Mission done!!!!!!!
It was the problem!!!!
I was under CG-NAT service and today morning I'm out of this service.....
I've just checked the ports were open and it WORKED!!!!!!! I'm using wireguard VPN server thanks to your support 

I'm really so happy !!!!!

Can I support or collaborate with your project  with a donation??????
And if the answer is yes...... How????

A lot of thanks for all your support!!!

**Comment by micahmo** [comment]
Hey @koliflores, I'm so glad to hear that this is resolved. The next step will be to ensure that everything continues to work after a restart. 😊

If you wish to donate, there is a Buy Me a Coffee link on my GitHub profile, but please never feel obligated to, especially since I can't always promise support. I just work on this project as a hobby.
